# Generated by Django 2.0.1 on 2018-03-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.TextField()),
                ('accesstoken_time', models.IntegerField()),
                ('expires_in', models.CharField(default=None, max_length=5)),
            ],
            options={
                'db_table': 'wx_acc',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=50, verbose_name='基金名')),
                ('fund_code', models.IntegerField(verbose_name='基金代码')),
                ('fund_get_state', models.BooleanField(default=0, verbose_name='是否获取')),
                ('fund_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fund_rise_fall', models.FloatField(blank=True, default=0, max_length=5, verbose_name='预估涨跌率')),
                ('fund_invest', models.FloatField(blank=True, default=0, max_length=5, verbose_name='投资额')),
                ('fund_pic_url', models.CharField(blank=True, default=None, max_length=255, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '基金',
                'verbose_name_plural': '基金',
                'db_table': 'wx_fund',
            },
        ),
    ]
