# Generated by Django 2.0.1 on 2018-03-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='expires_in',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
