# Generated by Django 2.0.1 on 2018-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wx', '0002_acc_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='accesstoken_time',
            field=models.IntegerField(),
        ),
    ]
